// ==============================================================================
// radarsim-engine — core/enums.hpp
// Error codes. Names and block layout match
// src/radarsimpy/includes/radarsimc.pxd:101-134 exactly; the Python layer maps
// TOO_MANY_RAYS_PER_GRID and PO_LUT_OVERFLOW to bespoke messages.
// ==============================================================================
#pragma once

enum RadarSimErrorCode {
    SUCCESS = 0,
    RADARSIMCPP_ERROR_NULL_POINTER = 1,
    RADARSIMCPP_ERROR_INVALID_PARAMETER = 2,
    RADARSIMCPP_ERROR_MEMORY_ALLOCATION = 3,
    RADARSIMCPP_ERROR_FREE_TIER_LIMIT = 4,
    RADARSIMCPP_ERROR_EXCEPTION = 5,
    RADARSIMCPP_ERROR_TOO_MANY_RAYS_PER_GRID = 6,
    RADARSIMCPP_ERROR_CUDA_DEVICE_QUERY = 7,
    RADARSIMCPP_ERROR_PO_LUT_OVERFLOW = 8,

    // PointSimulator CUDA errors
    RADARSIMCPP_ERROR_POINT_SIM_CUDA_SYNC = 100,
    RADARSIMCPP_ERROR_POINT_SIM_CUDA_KERNEL = 101,
    RADARSIMCPP_ERROR_POINT_SIM_FRAME_CUDA_SYNC = 102,
    RADARSIMCPP_ERROR_POINT_SIM_FRAME_CUDA_KERNEL = 103,

    // MeshSimulator CUDA errors
    RADARSIMCPP_ERROR_MESH_SIM_BASEBAND_CUDA_SYNC = 200,
    RADARSIMCPP_ERROR_MESH_SIM_BASEBAND_CUDA_KERNEL = 201,
    RADARSIMCPP_ERROR_MESH_SIM_BACKTRACING_CUDA_SYNC = 202,
    RADARSIMCPP_ERROR_MESH_SIM_BACKTRACING_CUDA_KERNEL = 203,

    // InterferenceSimulator CUDA errors
    RADARSIMCPP_ERROR_INTERF_SIM_CUDA_SYNC = 300,
    RADARSIMCPP_ERROR_INTERF_SIM_CUDA_KERNEL = 301,

    // LidarSimulator CUDA errors
    RADARSIMCPP_ERROR_LIDAR_SIM_CUDA_KERNEL = 400,
    RADARSIMCPP_ERROR_LIDAR_SIM_CUDA_SYNC = 401,

    // NoiseSimulator CUDA errors
    RADARSIMCPP_ERROR_NOISE_SIM_CUDA_KERNEL = 500,
    RADARSIMCPP_ERROR_NOISE_SIM_CUDA_SYNC = 501,

    // RcsSimulator CUDA errors
    RADARSIMCPP_ERROR_RCS_SIM_CUDA_KERNEL_VISIBLE = 600,
    RADARSIMCPP_ERROR_RCS_SIM_CUDA_KERNEL_RCS = 601,
    RADARSIMCPP_ERROR_RCS_SIM_CUDA_SYNC = 602,
};
